- name: configure backend
  hosts: backend
  become: yes
  vars:
    root_user: "{{root}}"
    mysql_root_password: "{{ExpenseApp@1}}"
    login_host: "{{mysql.hemanthk.online}}"
  tasks:
  - name: Install necessary packages
    yum:
        name:
          - openssh-clients
          - rsync
        state: present

  - name: Ensure /tmp is writable
    file:
        path: /tmp
        state: directory
        mode: '1777'

  - name: Ensure ec2-user home is writable
    file:
        path: /home/ec2-user
        state: directory
        mode: '0700'  
  - name: disable default nodejs version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable latest version of nodejs given by dev team
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package: 
      name: "{{item}}"
      state: present
    loop:
      - nodejs
      - mysql

  - name: create user expense
    ansible.builtin.user:
      name: expense

  - name: Ensure necessary packages for file transfers
    yum:
     name:
      - openssh-clients
      - rsync
     state: present

  - name: Ensure /tmp directory is writable
    file:
      path: /tmp
      state: directory
      mode: '1777'
      owner: root
      group: root

  - name: Ensure ec2-user home directory exists and writable
    file:
      path: /home/ec2-user
      state: directory
      mode: '0700'
      owner: ec2-user
      group: ec2-user

  - name: Force Ansible to use SCP (if SFTP missing)
    set_fact:
      ansible_scp_if_ssh: yes
