- name: create three instance for 3-tier architecture project
  
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    region: us-east-1
    subnet_id: "subnet-013b91028ac4cff48"
    sg_group: "sg-0644430e9f98939b1"
    zone: "hemanthk.online"
    instances:
    - mysql
    - backend
    - frontend
  
  tasks:
   - name: install boto3 and botocore
     ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
   - name: create ec2 instances
     amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: t3.micro
        security_group: "{{ sg_group }}"
        image_id: "{{ ami_id }}"
     loop: "{{ instances }}"
     register: ec2_instances

   - name: output of ec2_instances
     ansible.builtin.debug:
        msg: "{{ ec2_instances }}"
   
   - name: create r53 records
     amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private-ip_address}}"
      wait: true
      overwrite: true 
     loop: "{{ec2_instances.results}}"

   - name: create r53 records
     amazon.aws.route53:
      state: present
      zone: "{{zone}}"
      record: "{{zone}}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public-ip_address}}"
      wait: true
      overwrite: true 
     when: "{{item.item}} == frontend"

     

  



