- name: create three instance for 3-tier architecture project
  
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    region: us-east-1
    subnet_id: "subnet-013b91028ac4cff48"
    sg_group: "sg-0644430e9f98939b1"
    tags:
    instances:
    - mysql
    - backend
    - frontend
  
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name:
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: default
      image_id: "{{ ami_id }}"

  - name: install boto3 and botocore
    ansible.builtin.pip:
      name:
        - boto3
        - botocore

    register: result

  - name: output of ec2_instances
    ansible.builtin.debug:
      msg: "{{ result }}"


  



