- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansile.builtin.package:
      name: nginx
      state: present
  
  - name: run the service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  - name: remove file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download the frontend code
    ansible.builtin.get_url:
      url: curl -o /tmp/frontend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: extract the code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted