- name: configure mysql
  hosts: mysql
  become: yes
  vars:
    root_password: ExpenseApp@1
    root_user
  tasks:
  - name: install mysql package
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: change default root password
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
    
  